get http://localhost:8066/api/contactos
Accept: application/x-ndjson

###

get http://localhost:8066/api/contactos/1

### 4360

get http://localhost:8065/serie

###

get http://localhost:8065/paralelo
Accept: application/x-ndjson